---
- hosts: localhost
  connection: local
  gather_facts: no
  become: false
  roles:
    - rhtps.private-aws
  post_tasks:
    - meta: refresh_inventory

- hosts: bastions
  gather_facts: yes
  become: true
  roles:
    - rhtps.800-53