---
# defaults file for 800-53
audit_rules: /etc/audit/rules.d/audit.rules
audit_arch:
  - b32
  - b64
aide_minute: 05
aide_hour: 03
aide_day_of_month: '*'
aide_month: '*'
aide_day_of_week: '*'
shared_lib_path:
  - /lib
  - /lib64
  - /usr/lib
  - /usr/lib64
executables_path:
  - /bin
  - /usr/bin
  - /usr/local/bin
  - /sbin
  - /usr/sbin
  - /usr/local/sbin

ac_disable_services:
- autofs
- abrtd
- rdisc
- rexec
- rlogin
- rsh
- telnet
- tftp
- xinetd
- ypbind
- ypserv

ac_uninstall_packages:
- xinetd
- telnet-server
- rsh-server
- ypserv
- tftp-server

cm_disable_services:
- atd
- avahi-daemon
#- oddjobd
#- qpidd
- rdisc
- rexec
- rlogin
- rsh
- telnet
- tftp
- xinetd
- ypbind

cm_uninstall_packages:
- xinetd
- telnet-server
- rsh-server
- ypserv
- tftp-server

ia_disable_services:
- telnet
- rlogin
- rsh

vpn_package: openswan

run_scap: true
scap_profile:
- stig-rhel{{ ansible_distribution_major_version }}-server-upstream

scap_reports_dir: /tmp
