---
# vars file for private-aws
ec2_region: us-east-1
ec2_region_sidea: "{{ ec2_region }}a"
ec2_region_sideb: "{{ ec2_region }}e"
ec2_image: ami-2051294a
ec2_instance_type: m4.xlarge

private_cidr_b: 192.168.0.0/16
private_cidr_c_sidea: 192.168.1.0/24
private_cidr_c_sideb: 192.168.2.0/24

public_cidr_b: 10.0.0.0/16
public_cidr_c_sidea: 10.0.1.0/24

public_manifest:
  bastions:
    role: bastion
    type: t2.medium
    count: 1
    rootvol:
      size: 100
      type: gp2

private_manifest:
  webservers:
    role: webserver
    type: t2.medium
    count: 1
    rootvol:
      size: 10
      type: gp2
    volumes:
      - name: /dev/xvdb
        type: gp2
        size: 10